version: "3.8"

services:
  api:
    build: ./TTechEcommerceApi
    ports:
        - 5000:80
    depends_on:
        - db

  db:
    image: "mcr.microsoft.com/mssql/server:latest"
    ports:
        - 1433:1433
    
    environment:
        SA_PASSWORD: "123qwe!@#"
        ACCEPT_EULA: "Y"
        ASPNETCORE_URLS: http://+:5000